apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kestrel.gg_gametemplates.yaml
  - kestrel.gg_gameservers.yaml
  - kestrel.gg_backups.yaml
  - kestrel.gg_backupschedules.yaml
  - kestrel.gg_restores.yaml
  - kestrel.gg_modulesources.yaml
  - kestrel.gg_modules.yaml
