apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gameplane.local_gametemplates.yaml
  - gameplane.local_gameservers.yaml
  - gameplane.local_backups.yaml
  - gameplane.local_backupschedules.yaml
  - gameplane.local_restores.yaml
  - gameplane.local_modulesources.yaml
  - gameplane.local_modules.yaml
