---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - pods/ephemeralcontainers
  - pods/log
  - secrets
  - serviceaccounts
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - gameplane.local
  resources:
  - backups
  - backupschedules
  - clusters
  - gameservers
  - modulesources
  - networkcaptures
  - restores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gameplane.local
  resources:
  - clusters/status
  - gametemplates/status
  - modules/status
  - modulesources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gameplane.local
  resources:
  - gametemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gameplane.local
  resources:
  - modules
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gameplane.local
  resources:
  - modules/finalizers
  verbs:
  - update
- apiGroups:
  - metallb.io
  resources:
  - ipaddresspools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
