apiVersion: kestrel.gg/v1alpha1
kind: Backup
metadata:
  name: smp-01-manual-001
  namespace: kestrel-games
spec:
  serverRef:
    name: smp-01
  repoRef:
    name: kestrel-backup-repo
    key: url
  strategy: restic-snapshot
  quiesce: true
  tags:
    - manual
