apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kestrel_v1alpha1_gametemplate.yaml
  - kestrel_v1alpha1_gameserver.yaml
  - kestrel_v1alpha1_backup.yaml
  - kestrel_v1alpha1_backupschedule.yaml
