apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gameplane_v1alpha1_gametemplate.yaml
  - gameplane_v1alpha1_gameserver.yaml
  - gameplane_v1alpha1_backup.yaml
  - gameplane_v1alpha1_backupschedule.yaml
  - gameplane_v1alpha1_restore.yaml
  - gameplane_v1alpha1_modulesource.yaml
  - gameplane_v1alpha1_module.yaml
